/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.g12.duque.antonio.logica2;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 * 
 * @author Antonio
 */
public class JFTela extends javax.swing.JFrame {

    //Construtor: JFtela tela = new JFTela();
    public JFTela() {
        initComponents();
        txtValor1.setText("");
        txtValor2.setText("");
        txtResultado.setText("");
        txtResultado.setEditable(false);
        rbReal.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        btnInteiro = new javax.swing.JButton();
        btnLong = new javax.swing.JButton();
        btnFloat = new javax.swing.JButton();
        btnDouble = new javax.swing.JButton();
        btnCambio = new javax.swing.JButton();
        rbDolar = new javax.swing.JRadioButton();
        rbEuro = new javax.swing.JRadioButton();
        rbReal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Valor 1");

        txtValor1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtValor1.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Valor 2");

        txtValor2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtValor2.setText("jTextField2");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Resultado");

        txtResultado.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtResultado.setText("jTextField3");

        btnInteiro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnInteiro.setText("inteiro");
        btnInteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteiroActionPerformed(evt);
            }
        });

        btnLong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnLong.setText("long");
        btnLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLongActionPerformed(evt);
            }
        });

        btnFloat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnFloat.setText("float");
        btnFloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloatActionPerformed(evt);
            }
        });

        btnDouble.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnDouble.setText("double");
        btnDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleActionPerformed(evt);
            }
        });

        btnCambio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCambio.setText("Cãmbio");
        btnCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDolar);
        rbDolar.setText("Dolar");

        buttonGroup1.add(rbEuro);
        rbEuro.setText("Euro");

        buttonGroup1.add(rbReal);
        rbReal.setText("Real");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtValor1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(txtValor2))
                                .addGap(26, 26, 26)
                                .addComponent(btnInteiro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLong, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFloat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(btnDouble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbReal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInteiro)
                        .addComponent(btnLong)
                        .addComponent(btnFloat)
                        .addComponent(btnDouble)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnCambio)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDolar)
                    .addComponent(rbEuro)
                    .addComponent(rbReal))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteiroActionPerformed
        // Escreve teu código aqui ohh coisa meiga do profe!
        // Casting (alteração do tipo de dado)
        //De String para inteiro
        int valor1 = Integer.valueOf(txtValor1.getText());
        int valor2 = Integer.valueOf(txtValor2.getText());
        int resultado = valor1 + valor2;
        //Casting de Inteiro para String
        txtResultado.setText(String.valueOf(resultado));
        
    }//GEN-LAST:event_btnInteiroActionPerformed

    private void btnLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLongActionPerformed
        // TODO add your handling code here:
        long valor1 = Long.valueOf(txtValor1.getText());
        long valor2 = Long.valueOf(txtValor2.getText());
        long resultado = valor1 * valor2 - (valor2 + valor1);
        txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnLongActionPerformed

    private void btnFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloatActionPerformed
        // TODO add your handling code here:
        float preco = Float.parseFloat(txtValor1.getText());
        float quantidade = Float.parseFloat(txtValor2.getText());
        float total = preco * quantidade;
        String strTotal = String.valueOf(total);
        strTotal = strTotal.replace(".", ",");
        txtResultado.setText("R$ "+ strTotal);
    }//GEN-LAST:event_btnFloatActionPerformed

    private void btnDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoubleActionPerformed
        // TODO add your handling code here:
        final double DOLAR = 4.98;
        double valor = Double.valueOf(txtValor1.getText());
        txtValor2.setText("R$ "+ String.valueOf(DOLAR).replace(".", ","));
        double total = valor/DOLAR;
        DecimalFormat df = new DecimalFormat("US$ ,##0.00");
        String strTotal = df.format(total);
        txtResultado.setText(strTotal);
    }//GEN-LAST:event_btnDoubleActionPerformed

    private void btnCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioActionPerformed
         // TODO add your handling code here:
        final double DOLAR = 4.98;
        final double EURO = 5.41;
        double valor = Double.parseDouble(txtValor1.getText());
        double total = 0;
        
        if(rbDolar.isSelected()){
            total = valor/DOLAR;
            txtValor2.setText(String.valueOf(DOLAR));
        }
        
        if(rbEuro.isSelected()){
            total = valor/EURO;
             txtValor2.setText(String.valueOf(EURO));
        }
        
        if(rbReal.isSelected()){
             txtValor2.setText("R$ 1,00");
        }
        
        
    }//GEN-LAST:event_btnCambioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambio;
    private javax.swing.JButton btnDouble;
    private javax.swing.JButton btnFloat;
    private javax.swing.JButton btnInteiro;
    private javax.swing.JButton btnLong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbDolar;
    private javax.swing.JRadioButton rbEuro;
    private javax.swing.JRadioButton rbReal;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
